### PR TITLE
Listen for multiple signals

### LINKED ISSUE #42: Listen for multiple signals
Greetings.

I have recently started using this library and I'm liking it very much. It makes the application a whole lot cleaner.

I think that a useful enhancement would be the ability to listen for multiple signals and trigger the cleanup mechanisms on any of the signals specified.

I make this suggestion because of my recent experience, which was the following:
In a production setting, I agree that listening just for `SIGTERM` is probably sufficient.
However during development, I just kill my application using `control + c` which sends `SIGINT`.
Now to cater for this was simple enough. Based on an environment variable, at start up, I am able to give Terminus the appropriate signal to listen for (`SIGINT` or `SIGTERM`).
Next I added [Nodemon](https://github.com/remy/nodemon#nodemon) to my application, for use during development only. For those unfamiliar with Nodemon, it simply restarts your application when it detects a file change. Nodemon achieves this by sending a `SIGUSR2`. (their [docs](https://github.com/remy/nodemon#controlling-shutdown-of-your-script) on this).
With this setup, the application needs to listen for at least `SIGINT` and `SIGUSR2` in order for Nodemon to allow the application to cleanup properly before restarting it, and for the same to happen when `control + c` is used to kill the application.

I think that the above scenario is a pretty common setup used during development and it would be nice to be able to cater for similar scenarios without jumping through too many hoops (Eg. based on environment variables, do something "special" to make it all work). I also can't think of any downsides for the application cleanup logic to be triggered on multiple signals.

So if this is deemed to be a good idea, I am happy to attempt an implementation of this.

Thank you.

### PR DESCRIPTION
**Pull request by bgmike**
Fixes #42 

This is my attempt at addressing the issues described in #42

### CODE REVIEW

**Comment by gergelyke** [comment]
Thanks for the contribution @bgmike !

Could you add it to the docs too? Also, can we keep the `signal` option too, so it won't be a breaking change? What do you think?

**Comment by bgmike** [comment]
Hello @gergelyke 

Yes, I agree with your suggestions. I will extend the documentation to cover this capability, and refactor the code to allow for both multi-signal as well as the singular option.

**Comment by gergelyke** [comment]
cool, thanks a lot @bgmike !

**Comment by mvasilkov** [comment]
Note that in the current implementation, you appear to be initializing stoppable multiple times on the same server, and then promisifying server.stop multiple times, too. This might not be a huge issue, but there's certainly a cleaner way.

Also the cleanup function can be called several times. The onSignal and onShutdown callbacks have to either be aware of that, or we could make sure we're invoking them once at most.

**Comment by gergelyke** [comment]
good catch @mvasilkov !

**Comment by bgmike** [comment]
Hello @mvasilkov 

Thanks for the input. I'll keep this in mind when I refactor this.

**Comment by gergelyke** [comment]
@bgmike do you want to work on this, or should I finish it up?

**Comment by SeanLatimer** [comment]
I have this implemented in my fork, I could open a PR if this one doesn't get finished up

**Comment by gergelyke** [comment]
that'd be great @SeanLatimer

**Comment by SeanLatimer** [comment]
@gergelyke No problem, let me know when & I'll open a PR

**Comment by bgmike** [comment]
Hello @gergelyke 

My apologies for the delays, I've been swamped at work lately. I think lets use the implementation from @SeanLatimer

**Comment by gergelyke** [comment]
closing in favor of https://github.com/godaddy/terminus/pull/57

**Pull request closed without merging**
