### PR TITLE
feat(status-code): allow custom status codes

### PR DESCRIPTION
**Pull request by gergelyke**

### CODE REVIEW

**Review by sindilevich — COMMENTED** [review]
It is a marvelous solution! Much more elegant than mine is! Two questions here:

1. Why the call to `sendFailure` at `lib/terminus.js:68` was left unattended? Do we want to be able provide an option for a custom status code there too?
2. What should I do with my PR (https://github.com/godaddy/terminus/pull/187)? How'd I cancel it so you can advance yours?

Thank you!

**Comment by gergelyke** [comment]
@sindilevich thanks for your patience here - I'll clean up this draft PR sometimes this week. Will keep you posted!

**Comment by sindilevich** [comment]
Sure thing, @gergelyke, thank you!

**Comment by rxmarbles** [comment]
closing this PR as this was handled in #190

**Pull request closed without merging**
