### PR TITLE
Add cluster info and introduce useExit0

### PR DESCRIPTION
**Pull request by aeimer**
Adds some info on how to use this with cluster.
Adds option to exit with 0 if wanted. See #1

### CODE REVIEW

**Comment by aeimer** [comment]
@gergelyke Here we go, not yet tested. I may need some help with the tests. What do you think so far?

**Comment by gergelyke-dd** [comment]
thank you @aeimer! would it be possible to split this into two PRs? one for useExit0, and one for cluster? I am assuming useExit will be a lot simpler to review and test (and release)

**Comment by aeimer** [comment]
@gergelyke-dd well the cluster thing is only some help, no real code. But if you want to, sure.

**Comment by gergelyke-dd** [comment]
let's do that, thank you

**Comment by aeimer** [comment]
Closing as splitted MRs are pusehed

**Comment by gergelyke-dd** [comment]
thanks! I'll get back to you later today/tomorrow AM (PST)

**Pull request closed without merging**
