### PR TITLE
Feature: Expose an internal state to health checks

### PR DESCRIPTION
**Pull request by okv**
This PR implements #184

### CODE REVIEW

**Comment by gergelyke** [comment]
Looks great, thanks @okv ! Would you mind updating the TS types as well? Not a big deal if not, I'll take care of it in a follow up pr in that case

Let me know what you prefer

**Comment by okv** [comment]
@gergelyke please update it

**Comment by okv** [comment]
Hey @gergelyke ! Is there any chance that this PR will be merged? :smiley:

**Comment by okv** [comment]
Awesome news :rocket:  thanks a lot

**Pull request merged**
